config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get '/listings/map/:search', to: 'listings#search'
  resources :listings do
    resources :reviews
    resources :bookings, only: %i[show new create destroy] do
      resources :payments, only: [:new]
    end
  end

  get '/bookings', to: 'bookings#index'
  get '/manage', to: 'listings#manage'
  get '/payments/session', to: 'payments#get_stripe_id'
  get '/payments/success', to: 'payments#success'
  post '/payments/webhook', to: 'payments#webhook'
  root to: 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
# frozen_string_literal: true

require 'booking.rb'
require 'shared_methods.rb'

class Listing < ApplicationRecord
  include SharedMethods
  validates :title, :description, :category, :daily_rate, :hourly_rate, presence: true
  belongs_to :user
  belongs_to :location
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :image

  # def self.search(search)
  #   if search
  #     location = Location.find_by(city: search)
  #     @listings = Listing.includes(:tags).where('location.id' => image_tag.id).all
  #   else
  #     @listings = Listing.all
  #   end
  # end

  # def self.search_category(search)
  #   if search
  #     self.where(category: category)
  #   else
  #     @listings = Listing.all
  #   end
  # end

  # checks if a particular date is available for a listing
  def date_available?(date)
    bookings = Booking.where(listing_id: id)
    bookings.each do |booking|
      if booking.start_date < date && booking.end_date > date && booking.confirmed == true
        return false
      end
    end
    true
  end

  # checks availability for a listing within a range of dates
  def check_availability(start_date, end_date)
    bookings = Booking.where(listing_id: id)
    bookings.each do |booking|
      if date_to_integer(booking.start_date) < date_to_integer(start_date) &&
         date_to_integer(booking.end_date) > date_to_integer(end_date)
        return false
      end
    end
    true
  end

  # checks if a particular time of day is available
  def time_available?(time, date)
    bookings = Booking.where(listing_id: id)
    bookings.each do |booking|
      if booking.start_date == date && booking.end_date == date
        return false if booking.start_time <= time && booking.end_time >= time
      end
      if booking.start_date == date
        return false if booking.start_time <= time
      end
      next unless booking.end_date == date
      return false if booking.end_time >= time
    end
    true
  end

  # returns true if a date has some times available but is not fully available
  def partial_availability(date)
    bookings = Booking.where(listing_id: id)
    return false unless date_available?(date)

    bookings.each do |booking|
      return true if booking.start_date == date || booking.end_date == date
    end
    false
  end

  # finds times available for a particular date
  def get_available_times(date)
    bookings = Booking.where(listing_id: id)
    start_time = 0
    end_time = 24
    bookings.each do |booking|
      if booking.start_date == date
        end_time = booking.start_time if end_time > booking.start_time
      end
      next unless booking.end_date == date

      start_time = booking.end_time if start_time < booking.end_time
    end
    "#{date} : available from #{start_time}:00 to #{end_time}:00"
  end

  # gets the average rating for a listing based on its reviews
  def average_rating
    return 0 if reviews.empty?

    sum = 0
    reviews.each do |review|
      sum += review.rating
    end
    sum.to_f / reviews.length
  end
end

app/controllers/listings_controller.rb
# frozen_string_literal: true

class ListingsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_listing, only: %i[show edit update destroy]
  before_action :set_user_listing, only: [:edit]

  # displays listings based on search parameters
  def index
    @listings = []
    if params[:city] && params[:city] != ''
      # get locations that match the search params
      locations = Location.search_city(params[:city])
      coordinates = Geocoder.coordinates(params[:city])
    else
      locations = Location.all
    end
    # loop through all listings and check if it's location_id matches any locations
    # then add matching listings into listings array
    Listing.all.each do |listing|
      locations.each do |location|
        @listings << listing if listing.location_id == location.id
      end
    end
    if params[:start_date] && params[:end_date]
      if params[:start_date] != '' && params[:end_date] != ''
        # filter listings based on whether they are available within the dates
        @listings = @listings.filter { |listing| listing.check_availability(params[:start_date], params[:end_date]) }
      end
    end
    # order listing according to the type of sort selected in sort form
    @listings = if params[:sort_method] == '0'
                  # order by highest average rating
                  @listings.sort_by(&:average_rating).reverse
                else
                  # order by most ratings
                  @listings.sort_by { |listing| listing.reviews.length }.reverse
                end
    # map search bar
    # re-centers map based on search params
    if params[:type] == 'json'
      data = @listings.map do |listing|
        [listing.location.latitude, listing.location.longitude]
      end
      render json: { data: data, center: [data[0][0], data[0][1]] }
    end
  end

  def search
    # finds coordinates of location passed into search bar
    location = Geocoder.search(params[:search])[0].data['geometry']['location']
    @listings = Listing.all
    data = @listings.map do |listing|
      [listing.location.latitude, listing.location.longitude]
    end
    render json: { data: data, center: [location['lat'], location['lng']] }
  end

  # gets all the listings belonging to current user
  def manage
    @listings = current_user.listings
  end

  # show page for listing
  def show
    # new review form
    @review = Review.new
  end

  # renders new listing form
  def new
    @listing = Listing.new
    @location = Location.new
  end

  # creates a new listing
  def create
    # make a new location based on location params
    new_location = Location.new(location_params)
    # check to make sure no location already exists with same full address before saving  
    # if the location already exists, set new location to the first match (there should be only one match)
    if matching_locations(new_location).length > 0
      new_location = matching_locations(new_location).first
    else
    # if no matching location exists, save the new location 
      new_location.save
    end
    # create a new listing referenced to the current user, using listing params + new_location
    @listing = current_user.listings.create(listing_params.merge(location_id: new_location.id))
    if @listing.save
      redirect_to @listing
    else
      render :new
    end
  end

  # renders edit listing form
  def edit
    # gets the location for the listing to be edited so, that attributes relating to lisitng location can be updated
    @location = Location.find(@listing.location_id)
  end

  def update
    # get the listings location
    @location = Location.find(@listing.location_id)
    # make a new location with updated params
    new_location = Location.new(location_params)

    # check if any locations already match the new one 
    # if the location already exists, set new location to the first match (there should be only one match)
    if matching_locations(new_location).length > 0
      new_location = matching_locations(new_location).first
    else
    # if no matching location exists, save the new location 
      new_location.save
    end

    # if the location is different from the previous one, set the listings location to the new one
    if @location.full_address != new_location.full_address
      @listing.location_id = new_location.id
    end
    if @listing.update(listing_params)
      redirect_to @listing
    else
      render :edit
    end
  end

  # delete a listing
  def destroy
    @listing.destroy
    redirect_to listings_path
  end

  private

  # permit params for listing
  def listing_params
    params.require(:listing).permit(:title, :description, :category, :image, :instant_pickup, :hourly_rate, :daily_rate)
  end

  # permit params for location
  def location_params
    params.require(:location).permit(:address, :post_code, :city, :country, :listings, :latitude, :longitude)
  end

  # returns matching locations based on a locations full address
  # used in create/update to check if a new location needs to be created for a listing
  def matching_locations(new_location)
    Location.all.select { |location| location.full_address == new_location.full_address }
  end

  def find_listing
    @listing = Listing.find(params[:id])
  end

  # check if current user is the listing owner
  # used for authoriztion to edit, delete listings
  def set_user_listing
    id = params[:id]
    @listing = current_user.listings.find_by_id(id)
    if @listing.nil?
      redirect_to listings_path
    end
  end
end

app/helpers/listings_helper.rb
# frozen_string_literal: true

module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: @listing, local: true) do |form| %>
<div class="form-field">
    <%= form.label :title %>
    <%= form.text_field :title %>
</div>
<div class="form-field">
    <%= form.label :description %>
    <%= form.text_area :description %>
</div>
<div class="form-field">
    <%= form.label :category %>
    <%= form.select :category, ['road', 'mtb', 'city/commuter', 'traithlon/TT', 'cyclocross/gravel', 'cargo', 'other']%>
</div>
<div class="form-field currency-field">
    <%= form.label 'Hourly rate: $' %>
    <%= form.number_field :hourly_rate %>
</div>
<div class="form-field currency-field">
    <%= form.label 'Daily rate:  $' %>
    <%= form.number_field :daily_rate %>
</div>
<%= fields_for(@location) do |f| %>
    <div class="form-field">
        <%= f.label :address %>
        <%= f.text_field :address %>
    </div>

    <div class="form-field">
        <%= f.label :post_code %>
        <%= f.text_field :post_code %>
    </div>

    <div class="form-field">
        <%= f.label :city %>
        <%= f.text_field :city %>
    </div>

    <div class="form-field">
        <%= f.label :country %>
        <%= f.text_field :country %>
    </div>
<%end%>
<div class="form-field">
 
    <%= form.label :instant_pickup %>
     <%= form.check_box :instant_pickup, { checked: false }, 'true', 'false' %>
     <p>Bicycles available for instant pickup must be placed in an accessible location for 
    the user to access. It can be locked with a suitable combination lock which should be sent to the
    user up booking confirmation</p> 
 </div>  
<div class="form-field">
    <%= form.label :image %>
    <%= form.file_field :image, accept:'image/png,image/gif,image/jpeg,image/jpg' %>
</div>
<div class='actions'>
    <%= form.submit class: 'button blue-button' %>
</div>
<% end %>

app/views/listings/edit.html.erb
<div class="form-container new-listing">
<h1>Edit Listing</h1>
<%= render "form", listing: @listing %>

</div>

app/views/listings/index.html.erb
<div class="outer-container">
<div class="options-bar">
<div class="map-search">
<%= form_tag listings_path, method: 'get', id: "search-form", class: 'map-form' do %>
    <div class="search-field">     
      <%= text_field_tag :search, params[:search], id: "map-search-field" %>
    </div>
    <%= submit_tag "Search", name: nil, class: 'button blue-button', id: 'search-button' %>
 <%end%>
 </div>
<div class="search-bar">
    <%= form_tag listings_path, method: 'get', class: 'search-form' do %>
    <div class="search-field">
      
      <%= text_field_tag :city, params[:city], placeholder: "Enter city", id: "search-field" %>
    </div>
    <div class="search-field">
      
      <%= date_field_tag :start_date, params[:start_date], placeholder: "From", class: 'date-input' %>
    </div>
    <div class="search-field">
       
       <%= date_field_tag :end_date, params[:end_date], placeholder: "To", class: 'date-input'%>
    </div>
    <%# <div class="search-field">
       <%= label_tag(:instant_pickup, "Instant pickup available") %>
       <%# <%= check_box_tag(:instant_pickup, params[:instant_pickup]) %> 
    <%# </div> %> 
        
      <%= submit_tag "Search", name: nil, class: 'button blue-button' %>
    <%end%>
    </div>
    <form action="/listings" method="get" class="sort-form">
    <div class="sort-option">       
        <input type="radio" name="sort_method"value="0" checked/>
        <label for="sort_method">Highest Rated</label>
    </div>
    <div class="sort-option">      
        <input type="radio" name="sort_method" value="1"/>
        <label for="sort_method">Most Ratings</label>
    </div>
    <input type="submit" value="Sort" class="button edit-button">
    </form>
    
</div>



<div class="main-container">
<div class="map-container">
    <div style="height: 700px; width: 500px;" id="map"></div>
</div>
    <div class="listings-container">
    <div class="listings-header">
        <%if params[:search] %>
            <h2>Listings for <%=params[:search] != "" ? params[:search] : "Everywhere"%></h2>
        <%end%>
    </div>
        <% @listings.each do |listing| %>
            <div class="listing-container">
                <div class="image-container">  
                    <%= image_tag listing.image if listing.image.attached? %>
                </div>
                <div class="listing-info">
                    <%= link_to listing.title, listing, class: 'listing-title'%>
                    <p class="listing-description"><%=listing.description%></p>                    
                    <div class="details-container">
                        <p>Category: <%=listing.category%></p>
                        <p>Hourly rate: $<%=listing.hourly_rate%></p>
                        <p>Daily rate: $<%=listing.daily_rate%></p>
                    </div>
                </div>
            </div>
        <%end%>
    </div>

</div>
<%= javascript_pack_tag "leaflet/index" %>
</div>

app/views/listings/manage.html.erb
<div class="manage-container">
<h1>My Listings</h1>
<div class="manage-listings-container">
    <% @listings.each do |listing| %>
     <div class="manage-listing-container">
    <h2><%=link_to listing.title, listing %></h2>
    <%= image_tag listing.image if listing.image.attached? %>
    <p><%=listing.bookings.length%> bookings</p>
        <div class="links-container">
            <%= link_to "Edit", "/listings/#{listing.id}/edit", class: 'button' %>
            <%= link_to "Manage Availability", "/listings/#{listing.id}/bookings/new", class: 'button'%>
            <%= link_to "Delete", @listing , method: :delete, class: 'button'%> 
        </div>
    </div>
    <%end%>
</div>
</div>

app/views/listings/new.html.erb
<div class="form-container new-listing">
<h1>New Listing</h1>
 <%= render "form", listing: @listing %>
</div>

app/views/listings/show.html.erb
<div class="show-container">
<div class="calendar-container">
    <div class="calendar-content">
        <h3>Availability</h3>
        <div class="calendar">
            <div>Mon</div>
            <div>Tue</div>
            <div>Wed</div>
            <div>Thur</div>
            <div>Fri</div>
            <div>Sat</div>
            <div>Sun</div>
            <%(Date.today..Date.today + 31).each do |date| %>
                <% if !@listing.date_available?(date)%>
                <div class="booked">
                    <p><%=date.day%></p>
                </div>
                <%elsif @listing.partial_availability(date)%>
                <div class="partial">
                    <p><%=date.day%></p>
                </div>
                <%else%>
                <div class="available">
                    <p><%=date.day%></p>
                </div>
                <%end%>
            <%end%>
        </div>
        <div class="calendar-keys">
            <div class="calendar-key">
                <div class="box" id="available-key"></div>
                <p>Available all day</p>
            </div>
            <div class="calendar-key">
                <div class="box" id="partial-key"></div>
                <p>Some times available</p>
            </div>
            <div class="calendar-key">
                <div class="box" id="booked-key"></div>
                <p>Not available</p>
            </div>
        </div>
        </div>
    </div>
    <div class="listing-container">
        <h1 class="listing-title"><%=@listing.title%></h1>
        <%= image_tag @listing.image if @listing.image.attached? %>
        <p><%=@listing.description%></p>
        <p>Category: <%=@listing.category%><p>
        <p>Hourly Rate: $<%=@listing.hourly_rate%></p>
        <p>Daily Rate: $<%=@listing.daily_rate%></p>
        <%if @listing.instant_pickup %>
            <p>Instant Pickup Available</p>
        <%end%>
        <%= link_to current_user == @listing.user ? 'Manage Availability' : 'Make Booking', new_listing_booking_path(@listing), class: 'button blue-button' %>
        <% if user_signed_in? && current_user == @listing.user %>
            <%= link_to "Edit", edit_listing_path, class: 'button edit-button' %>
            <%= link_to "Delete", @listing , method: :delete, class: 'button delete-button',  :data => {:confirm => 'Are you sure?'}%>  
        <%end%>
        <% if user_signed_in? && current_user != @listing.user %>
        <div class="review-form-container">
            <h3>Leave a review</h3>
            <%= form_for [@listing, @review] do |form| %>
            <div class="form-field">
                <%= form.text_area :body, class: 'review-body'%> 
            </div>
            <div class="form-field">
                <%= form.label :rating %>
                <%= form.select :rating, ['5','4','3','2','1']%>
            </div>
            <div class='actions'>
                <%= form.submit 'Submit', class: 'button blue-button'%>
            </div>
            <% end %>
        </div>
        <% end %>
        <% if user_signed_in? && current_user == @listing.user %>
        <h3>Current bookings</h3>
            <%@listing.bookings.each do |booking|%>
                <p>Booked by <%=booking.user.name%></p>
                <p>From: <%=booking.start_date%> at <%=booking.start_time%>:00</p>
                <p>To: <%=booking.end_date%> at <%=booking.end_time%>:00</p>
                <p>Contact user: <%=booking.user.email%></p>
            <%end%>
        <%end%>

        <div class="reviews-container">
            <h3>Reviews</h3>
            <% @listing.reviews.each do |review| %>
            <div class="review-container">
            <p><%=review.user.name%>: <%=review.body%></p>
            <p>Rating: <%=review.rating%></p>
            <%if user_signed_in? && current_user.id == review.user_id %>
            <%= link_to 'Delete', listing_review_path(@listing, review), method: :delete, class: 'button' %>
            <%end%>   
        <% end %>
        </div>
    </div>
</div>






 