config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get '/listings/map/:search', to: 'listings#search'
  resources :listings do
    resources :reviews
    resources :bookings, only: %i[show new create destroy] do
      resources :payments, only: [:new]
    end
  end

  get '/bookings', to: 'bookings#index'
  get '/manage', to: 'listings#manage'
  get '/payments/session', to: 'payments#get_stripe_id'
  get '/payments/success', to: 'payments#success'
  post '/payments/webhook', to: 'payments#webhook'
  root to: 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_calendar.html.erb
<div class="calendar-container">
    <div class="calendar-content">
        <h3>Availability</h3>
        <div class="calendar">
            <div>Mon</div>
            <div>Tue</div>
            <div>Wed</div>
            <div>Thur</div>
            <div>Fri</div>
            <div>Sat</div>
            <div>Sun</div>
            <%(Date.today..Date.today + 31).each do |date| %>
                <% if !@listing.date_available?(date)%>
                <div class="booked">
                    <p><%=date.day%></p>
                </div>
                <%elsif @listing.partial_availability(date)%>
                <div class="partial">
                    <p><%=date.day%></p>
                </div>
                <%else%>
                <div class="available">
                    <p><%=date.day%></p>
                </div>
                <%end%>
            <%end%>
        </div>
        <div class="calendar-keys">
            <div class="calendar-key">
                <div class="box" id="available-key"></div>
                <p>Available all day</p>
            </div>
            <div class="calendar-key">
                <div class="box" id="partial-key"></div>
                <p>Some times available</p>
            </div>
            <div class="calendar-key">
                <div class="box" id="booked-key"></div>
                <p>Not available</p>
            </div>
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer>
</footer>

app/views/shared/_nav.html.erb
<nav>
    <div class="nav-left">
    <%= link_to "BikeFinder", listings_path, id: 'nav-logo' %>
    <% if !user_signed_in? %>
    </div>
    <%end%>
    <% if user_signed_in? %>
        <%= link_to "Add Listing", new_listing_path %>
        <%= link_to "Manage Listings", '/manage' %>
        <%= link_to "View my bookings", bookings_path %>
    </div>
    <div class="nav-right">
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    </div>           
    <% else %>
    <div class="nav-right">
        <%= link_to "Login", new_user_session_path %>
        <%= link_to "Signup", new_user_registration_path %>
    </div>
    <% end %>
</nav>